# Version: 0.0.1
FROM node:0.10
MAINTAINER Tyler Fitch "automationtools@tfitch.com"
EXPOSE 3000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install
COPY app.js /usr/src/app/

CMD [ "npm", "start" ]
