---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  #- name: ubuntu-12.04
  - name: precise32
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

suites:
  - name: default
    run_list:
      - recipe[automation-tools::default]
    attributes:
